name: Auto Deploy Portfolio

on:
  push:
    branches:
      - Apps-addition
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Git Identity
        run: |
          git config --global user.name "ChiefDNA"
          git config --global user.email "ngabiranodaniel74@gmail.com"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to gh-pages Branch
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g gh-pages
          gh-pages -d build -b gh-pages -r https://$TOKEN@github.com/ChiefDNA/portfolio.git
